ER図の作成
YuzukiEndo/README_01 pull request #3
Opened 2024-07-12 08:23 UTC by YuzukiEndo

ER図を作成しました。
見難いかもしれませんが、ご確認よろしくお願いいたします。

2024-07-12 08:24 UTC, Tsuchiya2 commented
他の講師もER図の変遷が分かるようにしたいので、コメント欄に最新のER図のスクリーンショットを画像が表示される形で掲載をお願いいたします。（Gyazo・マークダウン）

2024-07-12 08:36 UTC, YuzukiEndo commented
![最新のER図](https://gyazo.com/6ea5b9315e330f9de74f0172698e72aa)

こちらで大丈夫ですかね・・・？
よろしくお願いします！

2024-07-12 08:36 UTC, YuzukiEndo commented
![最新のER図](https://gyazo.com/6ea5b9315e330f9de74f0172698e72aa)

2024-07-12 08:36 UTC, YuzukiEndo commented
![最新のER図](https://gyazo.com/6ea5b9315e330f9de74f0172698e72aa.png)

2024-07-12 08:37 UTC, YuzukiEndo commented
![最新のER図](https://gyazo.com/6ea5b9315e330f9de74f0172698e72aa.png)

これで大丈夫ですかね・・・？
よろしくお願いします！

2024-07-12 10:54 UTC, kashiwagi-rena commented
掲載確認取れました。問題ないです。
以下、コメントです。

---

- 認証機能は、どのgemをしようするのでしょうか？また、認証機能に必要なカラムは揃っているか確認しましょう。

- DailyNutritionGoalsテービルはどのように使用するでしょうか？Usersテーブルに性別や年齢、運動量の記載がないため、紐付けて取ってこれないと思いました。

2024-07-13 06:22 UTC, YuzukiEndo commented
ご確認ありがとうございます！　コミットID：864d74d226faf7c391e4ecbd146c51144a613b2bにて　以下の修正をしました。
認証機能：Sorcery gemを導入しました。
栄養管理の変更：DailyNutritionGoalsテーブルを削除しました。
栄養素確認画面に、一般的な成人の男女別推奨ガイドラインを記述するように変更しました。（注：正確な計算式を知らず、不用意な結果を出すのを防ぐため、一般的なガイドラインを提示することにしました）
食材入力方法の改善：カンマ区切りでの入力から、検索機能付きドロップダウンでの選択に変更しました。
ER図が全体的に間違っていると判断し、作り直しました。

わかりにくい＆間違っていて、お手数おかけして大変申し訳ございません・・・
よろしくお願いいたします。

![ER図](https://gyazo.com/74e3f80b2026af21a0306e60f0289363.png)

2024-07-14 09:01 UTC, tarakish requested changes
修正確認しました。
各カラムについてはデータ型も記載するようにしていただけますか？？

2024-07-16 02:20 UTC, YuzukiEndo commented
ご確認ありがとうございます！ 
コミットID: c0d99f2730ec20633658fa02a0fa2dfe7b80c064 にて、以下の修正をしました。
・カラムにデータ型を記述

お手数ですがご確認よろしくお願いいたします。

![ER図](https://gyazo.com/6a0af2b56ab579761aea875da6d37edc.png)

2024-07-16 03:26 UTC, Tsuchiya2 commented
概ね良いかと思います。LGTMです。
修正が必要になった際は適宜修正して開発を進めましょう。

2024-07-16 03:28 UTC, merged